### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Second Name",
  "email": "second@test.com",
  "password": "password",
  "password_confirmation": "password"
}


### Index
GET http://localhost:3000/records.json


### Create
POST http://localhost:3000/records.json
Content-Type: application/json

{
  "album_title": "test-artist",
  "artist": "test-album",
  "price": 50
}


### Show
GET http://localhost:3000/records/2.json



### Update
PATCH http://localhost:3000/records/4.json
Content-Type: application/json

{
  "price": 25
}



### Destroy
DELETE http://localhost:3000/records/4.json